name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  create-deployment-artifacts:
    name: Create Deployment Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile CSS and JavaScript
        run: |
          npm install
          npm run production
      - name: Configure PHP 8.0
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: mbstring, intl, pdo_mysql, zip, gd, exif, pcntl, bcmath, soap, curl, dom, fileinfo, json, xml, ctype, iconv, tokenizer, simplexml
      - name: Install Composer dependencies
        run: | 
          composer install --no-dev --no-interaction --prefer-dist
